### ISSUE TITLE
Cannot find the correct GLIBC version for Mongo installation

### ISSUE THREAD

**Issue by apurvakalia** [llmware-ai/llmware#410]
I am on a Linux machine with version details:

uname -a
Linux 4.18.0-425.19.2.el8_7.x86_64 #1 SMP Fri Mar 17 01:52:38 EDT 2023 x86_64 x86_64 x86_64 GNU/Linux

I installed llmware, and upon running the first example it fails to read in PDF files because:

mod_pdf = cdll.LoadLibrary(_path_pdf)
(Pdb) n
OSError: /lib64/libc.so.6: version `GLIBC_2.34' not found (required by /data/miniconda3/envs/start/lib/python3.9/site-packages/llmware/lib/linux/x86_64/llmware/../llmware.libs/libmongoc-1-3294a51b.0.so.0.0.0)

Looks like Mongo expects GLIBC_2.34 but what I have is:

ls -l /lib64/libc.so.6
lrwxrwxrwx. 1 root root 12 Sep 20 06:52 /lib64/libc.so.6 -> libc-2.28.so

Any ideas on how to fix this?

**Comment by doberst** [comment]
@apurvakalia - yes, we saw this issue recently on Ubuntu 20 - and the solution was either (a) upgrade the GLIBC (which is generally not recommended due to other system dependencies) or (b) update and use Ubuntu 22.      What Linux package and version are you using?

**Comment by apurvakalia** [comment]
I am on a shared machine which uses the following Linux install:

cat /etc/os-release
NAME="Red Hat Enterprise Linux"
VERSION="8.7 (Ootpa)"
ID="rhel"
ID_LIKE="fedora"
VERSION_ID="8.7"
PLATFORM_ID="platform:el8"
PRETTY_NAME="Red Hat Enterprise Linux 8.7 (Ootpa)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:8::baseos"
HOME_URL="https://www.redhat.com/"
DOCUMENTATION_URL="https://access.redhat.com/documentation/red_hat_enterprise_linux/8/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 8"
REDHAT_BUGZILLA_PRODUCT_VERSION=8.7
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="8.7"

**Comment by doberst** [comment]
@apurvakalia - thanks for sharing these details on the OS and version ... please give us 1-2 days - we will test on that platform, and recompile the drivers for that platform .... Will update this issue thread with progress...

**Comment by doberst** [comment]
@apurvakalia - we have back compiled all of our shared libraries back to Ubuntu 20 and GLIBC 2.31, but at this point, do not plan to back compile to versions earlier than that on Linux.   We support 6 major OS platforms currently (Mac Metal, Mac x86, Windows x86, Windows CUDA, Linux x86, Linux CUDA) ... and it becomes a challenge to effectively test and support much beyond that.   If you have a hard requirement still for RHAT 8.7 or another specific older version of Linux, could you let us know, and we would be happy to work with you - but would probably do it as a one-time build that we would make available for pull directly from the repo, rather than including in the pip install build.   I am closing the issue - but please raise again if you can not find a workable OS platform/version among our existing options.   Thanks again!
