### ISSUE TITLE
SLIM sentiment tool results seem random?

### ISSUE THREAD

**Issue by e-ave** [llmware-ai/llmware#416]
I keep running the same query and each time the response is different, even though the tokens and confidences are the same. 

For example, I tried it with a random reddit front page post title "Gen Z paid for it. We deserve what we fucking paid for."

Half of the time the result is negative:
```
{'choices': [('positive', 1066, 0.47514017642001743),
              ('negative', 22198, 0.4709914211528822),
              ('neutral', 17821, 0.05171089966686686)],
  'confidence_score': 0.4709914211528822,
  'dict_output': True,
  'llm_response': {'sentiment': ['negative']}}
```
But the other half of the time its positive:
```
{'choices': [('positive', 1066, 0.47514017642001743),
             ('negative', 22198, 0.4709914211528822),
             ('neutral', 17821, 0.05171089966686686)],
 'confidence_score': 0.47514017642001743,
 'dict_output': True,
 'llm_response': {'sentiment': ['positive']}}
```
I think it is negative, but it's more confident in positive, so why isn't it always returning positive?

**Comment by doberst** [comment]
@e-ave - will look into this -  quick response:  it is a notable example that the positive and negative logit choices are virtually identical values - since there is sampling, there will be a small stochastic element to each token generation (among the top logit choices), and if the choices are virtually identical in probability, then sometimes it will generate "positive" and sometimes "negative" ...

**Comment by NYDocutest** [comment]
Also, the text even to a human isn't clear whether it is positive or negative... The first sentence seems positive, and the second sentence seems negative. But then again, the second sentence could also be enforcing the positive attitude of the first sentence. Read another way both sentences could be read negatively. I don't think it is a good example.
