### ISSUE TITLE
SLIM sentiment: Sometimes top choice isn't selected

### ISSUE THREAD

**Issue by mneedham** [llmware-ai/llmware#445]
Hey,

I find sometimes with the SLIM sentiment model it doesn't select the top choice as the response. Below is the code:

```python
from llmware.agents import LLMfx

llm_fx = LLMfx(verbose=False)
llm_fx.load_tool("sentiment")
llm_fx.sentiment("You REALLY need to get new problems to pose to these models. Of course all these older examples are now in the training / fine-tuning data.")
```

And the response:

```python
{
    'llm_response': {'sentiment': ['neutral']},
    'dict_output': True,
    'confidence_score': 0.34393605021778545,
    'choices': [
        ('negative', 22198, 0.5064252181766817),
        ('neutral', 17821, 0.34393605021778545),
        ('positive', 1066, 0.14851506132425493)
    ]
}
```

I think it should select negative as that has the highest confidence?

**Comment by lubomirovna** [comment]
I have the same problem.

**Comment by doberst** [comment]
@mneedham & @lubomirovna - thanks for raising this - after a lot of exploration and experimentation, we have made updates in the model load process to allow for configuration with sample=False - which will result in deterministic generation.   We learned a lot in the process and put out a couple of videos on the topic too.   Check out the [example](https://github.com/llmware-ai/llmware/blob/main/examples/Models/adjusting_sampling_settings.py) as well as the [video][(](https://youtu.be/iXp1tj-pPjM?si=4fauK9P49c22H82x) ... this code is in pip install llmware==0.2.6 (or you can clone the latest repo).   Thanks again - and please let us know how it turns out with 'sample=False'
