### ISSUE TITLE
Library().delete_library does not delete the library

### ISSUE THREAD

**Issue by geverl** [llmware-ai/llmware#755]
The following code outputs "1" and "Library exists" whereas the expected output would be "1" and "Library does not exist".
```
LLMWareConfig().set_active_db("sqlite")
LLMWareConfig().set_vector_db("chromadb")
library_name = "lib1_library"
print(Library().delete_library(library_name=library_name)) # prints 1
if Library().check_if_library_exists(library_name):
    print("Library exists")
else:
    print("Library does not exist")
```

**Comment by MacOS** [comment]
Hi @geverl!

Thank you for reporting that issue!

May I ask which ```llmware``` version you used?

**Comment by doberst** [comment]
@geverl - thanks for raising this - and appreciate a nice clear simple example (sometimes the most simple example produces the bug that you missed!) ....   I am running the same script (copy and paste) - and getting the correct answer "Library does not exist" ... there is a typo in your script `LMWareConfig().set_active_db("sqlite")` which I did correct to `LLMWareConfig().set_active_db("sqlite")` ... could you please try to run this again?    Will keep the issue open.

**Comment by MacOS** [comment]
I think we should add a test case for this first.

**Comment by doberst** [comment]
@geverl - thanks for highlighting this - it is a good catch.   It has been fixed in the main branch if you pull the latest code, and will be in the next pip install release (in the next couple of days).   Two issues:   

(1) to delete the library, please pass "confirm_delete=True", e.g.,      `Library().delete_library(library_name=library_name,confirm_delete=True)`

(2) the bug in LLMWare was brought out by creating a fresh Library() object (which has been fixed now), rather than using the 'library state' built when creating the library.   Instead, if you modify your current code to:

    library = Library().create_new_library(library_name)
    print(library.delete_library(library_name=library_name, confirm_delete=True))

then, I believe it should work even with llmware==0.2.15.

Could you please check and confirm back and then we will close out the issue.
